### PR TITLE
fix: changed nyc example 🦄 

### PR DESCRIPTION
**Pull request by BeauBouchard**
Of the following [reports available for NYC](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-reports/lib), I believe most people prefer `text-lcov`, as it generates a robust text only report report.

`text-lcov` could be used for the purposes of piping the output directly to a service like codecov, vs., `lcov` which places a file on disk which you can work with.

the other examples of `coveralls.io` include this in their [examples](https://www.npmjs.com/package/coveralls#nyc), I think codecov should also use it for their example.

### CODE REVIEW

**Comment by stevepeak** [comment]
Thank you for the PR. I notice that [the uploads](https://codecov.io/gh/codecov/example-node/commit/65c56b51972b498de06df3646d718e781d6b2d03/build) include both lcov and json.

What is the difference between `text-lcov` and `lcov`? The words suggest they are the same....

**Comment by BeauBouchard** [comment]
If you take a look at the output for `lcov` and `text-lcov` 
`text-lcov` purposefully only outputs text (as an alternative to `lcov` which writes the report to disk)
The idea was that `text-lcov` could be used for the purposes of piping the output directly to a service like codecov, vs., `lcov` which places a file on disk which you can work with.

I revised my above description to be more clear. I think it made it sound like they were totally different.

**Comment by stevepeak** [comment]
👍 Fantastic. Thank you for clarifying the difference.

`nyc report --reporter=lcov` would this put the coverage in the `coverage/lcov.info` and `coverage/coverage.json` files?

We primary reply on the json data and use the lcov as a backup.

**Comment by BeauBouchard** [comment]
> would this put the coverage in the `coverage/*`?

no, it would just pipe it or display it. 

 I found `--text-lcov` is a little bit preferable when setting up an example, as its purpose is sort of for exporting to a coverage summary tool, or being displayed in a ci tool log. But that is just a subjective option.

**Comment by stevepeak** [comment]
Thank you! I'll accept that change 👍

**Pull request merged**
