### PR TITLE
Simplify Jest example

### PR DESCRIPTION
**Pull request by cmalard**

### CODE REVIEW

**Comment by thomasrockhu** [comment]
Thanks here @cmalard, closing out in favor of https://github.com/codecov/example-node/pull/42

**Comment by cmalard** [comment]
I would have appreciated to be listed as [contributor](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github), but well at least it's merged 😉🍻

**Comment by thomasrockhu** [comment]
Oof @cmalard this is my mistake, how can we best remedy this?

**Comment by cmalard** [comment]
[(probably not a good idea 🙈)](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message)

**Pull request closed without merging**
