### PR TITLE
Updated the README

### PR DESCRIPTION
**Pull request by TomPed**
Updated the README to follow standards. Are the any language specific caveats that need to be added?

### CODE REVIEW

**Comment by stevepeak** [comment]
Thanks @TomPed -- Node is a little unique, there is a specific node uploader at https://github.com/codecov/codecov-node

See inline comments for more details.

**Comment by TomPed** [comment]
Looks like there were a few versions for `.travis.yml` for node, I snagged this from the original `README.md`.

**Comment by TomPed** [comment]
I took a look into why Travis is failing. Here is the error:
```
/home/travis/build/codecov/example-node/node_modules/codecov/node_modules/request/node_modules/hawk/node_modules/hoek/lib/index.js:371
exports.unique = (array, key) => {
                              ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/codecov/example-node/node_modules/codecov/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5:14)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
```
Looks like this package is using es6 arrow functions and the job can't parse it.

**Comment by stevepeak** [comment]
Need to add a link to https://github.com/codecov/example-typescript

**Comment by TomPed** [comment]
Updated.

**Pull request merged**
